services:
  
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: volunteer_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
   
volumes:
  db_data:
