### Variables 
@apiurl = http://localhost:3000/api/


###
PATCH http://localhost:3000/psicologo/bd0fcd79-53c9-4c00-8d5c-3b2cba88dcdc/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODY5MDY1MjcsImV4cCI6MTc4NjkwNzAwN30.qCimE3Ae9okFznSWJOLoDdF7mvNFKq3h3-OZqtodwoU


###

POST http://localhost:3000/api/forgot-password
Content-Type: application/json
# Authorization: Bearer ACCESS-TOKEN

{
    "email": "juelma@gmail.com"
}
###
POST http://localhost:3000/api/reset-password
Content-Type: application/json
# Authorization: Bearer ACCESS-TOKEN

{
    "email": "juelma@gmail.com",
    "code":"2966",
    "newPassword":"admin123"
}

###
PATCH http://localhost:3000/api/psicologo/d543d30a-1249-4c00-af2e-394493efdacd/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODY5Nzc1NDcsImV4cCI6MTc4Njk3ODAyN30.Bh8-lqUSIpuQEyDEz89qyKKMXa-h80IEqNh6Okdt-0s
Content-Type: application/json

###
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "email": "teste@example.com",
    "password": "Teste123_",
    "role": 2,
    "nome": "John",
    "sobrenome": "Mark Doe"
}
###
GET http://localhost:3000/api/dashboard/users


###
GET http://localhost:3000/api/psicologo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODY5NzcyMjEsImV4cCI6MTc4Njk3NzcwMX0.PzUNKBYRNzPxnfvFHRPSNnuhfwqj7cePLoQTIqvxHAo

###
POST http://localhost:3000/api/psicologo
Content-Type: application/json

{
  "especialidade": "Psicologia clínica",
  "numero_ordem": "01010101111",
  "user": {
      "email": "lura@example.com",
      "password": "User123_",
      "nome": "Lura",
      "sobrenome": "Nunes"
  }
}

###

POST http://localhost:3000/api/paciente
Content-Type: application/json

{
  "telefone": "940019234",
  "idade":25,
  "user": {
      "email": "anaww@example.com",
      "password": "AnaLima123_",
      "role": 0,
      "nome": "Ana Silva",
      "sobrenome": "Lima"
  }
}

###
GET http://localhost:3000/api/pareamento
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODQ4MTU5NzcsImV4cCI6MTc4NDgxNjQ1N30.CnjqsrMhXbqINShD-HOrCta0DASypgdXpszZfyFW04Y
###

PATCH http://localhost:3000/api/sessao/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODQ4MTU5NzcsImV4cCI6MTc4NDgxNjQ1N30.CnjqsrMhXbqINShD-HOrCta0DASypgdXpszZfyFW04Y

{
     "sessao_id": "0945ffb2-70ed-40ad-a14f-a387ae8c536e"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"anaww@example.com",
    "password":"User123_"
}

### post
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNjFlNTM4LTE4ZmItNDhiYi1hMmFlLTMzNTE3MDQwMjg1NiIsInJvbGUiOjEsIm5vbWUiOiJBdXJvcmEgQ2FiZWNoZSIsImlhdCI6MTc4Mjg1NzY0OSwiZXhwIjoxNzgyODU4MTI5fQ.YEebn6AqPpcCktcO7hEb2w_6-ZZHGTzEPEOU753CamM

{
    "content":"Perdoe-se sempre", "hastags":"saude, bem-estar", "photoUrl":"foto de teste", "psicologo_id":"083392da-1e36-4d0c-854d-f15feab09665"
}

#### Refresh token

POST http://localhost:3000/api/refresh
Content-Type: application/json

{
    "refresh":"a88d7720-fc03-4602-84f3-dcad913ed737"
}

###
POST http://localhost:3000/api/forgot-password
Content-Type: application/json


{
    "email":"milton@yahoo.com"
}

###
 
POST http://localhost:3000/api/reset-password
Content-Type: application/json


{
    "email":"milton@yahoo.com",
    "code":"3391",
    "newPassword":"Milton123_"
}

###
GET http://localhost:3000/api/psicologo/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODY5NzcyMjEsImV4cCI6MTc4Njk3NzcwMX0.PzUNKBYRNzPxnfvFHRPSNnuhfwqj7cePLoQTIqvxHAo