### Variables 
@apiurl = http://localhost:3000/api/


###

POST http://localhost:3000/api/forgot-password
Content-Type: application/json
# Authorization: Bearer ACCESS-TOKEN

{
    "email": "juelma@gmail.com"
}
###
POST http://localhost:3000/api/reset-password
Content-Type: application/json
# Authorization: Bearer ACCESS-TOKEN

{
    "email": "juelma@gmail.com",
    "code":"2966",
    "newPassword":"admin123"
}

###
GET http://localhost:3000/api/vinculo/bb0d208c-4021-4901-8741-a5ec63419ec5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODc3MTExNzYsImV4cCI6MTc4NzcxMTY1Nn0.wpfw0TSn7T8giC6SCxhHIYtjLzC7751XJU4PecYhrAQ

### psicologos sessao
GET http://localhost:3000/api/sessao/bb0d208c-4021-4901-8741-a5ec63419ec5/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODgzMTAxOTksImV4cCI6MTc4ODMxMDY3OX0.dKlgZS4QISU3tVggCr11czJ7xBAn1CSOx83D0HslELw
Content-Type: application/json

### pacientes sessao
GET http://localhost:3000/api/sessao/paciente/0546331d-3e13-43c5-8b33-903c7aa885ad/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODgzOTIzMTcsImV4cCI6MTc4ODM5Mjc5N30.vWPHCbGNG_X6pFQHkQ0YgDJl1UXRTN9WSmmV-epzpvQ
Content-Type: application/json

###

GET http://localhost:3000/api/sessao/bb0d208c-4021-4901-8741-a5ec63419ec5/pedidos/accepted
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODc2OTEyMDgsImV4cCI6MTc4NzY5MTY4OH0.W0hsIy5m8laJEO3ERF2hYU3tFRIbsPtNhVUWCDIlCgQ

###
POST http://localhost:3000/api/psicologo
Content-Type: application/json

{
  "especialidade": "Psicologia clínica",
  "numero_ordem": "01010101111",
  "user": {
      "email": "lura@example.com",
      "password": "User123_",
      "nome": "Lura",
      "sobrenome": "Nunes"
  }
}

###

POST http://localhost:3000/api/paciente
Content-Type: application/json

{
  "telefone": "940019234",
  "idade":25,
  "user": {
      "email": "anaww@example.com",
      "password": "AnaLima123_",
      "role": 0,
      "nome": "Ana Silva",
      "sobrenome": "Lima"
  }
}

###
GET http://localhost:3000/api/pareamento
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODQ4MTU5NzcsImV4cCI6MTc4NDgxNjQ1N30.CnjqsrMhXbqINShD-HOrCta0DASypgdXpszZfyFW04Y


###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"anaww@example.com",
    "password":"User123_"
}

####
GET http://localhost:3000/api/psicologo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODkwNjkxMTMsImV4cCI6MTc4OTA2OTU5M30.8EcJZP95AXILfgtwndi9Via9zfU3Jqe8ImfKPc05i4o

#### Refresh token

POST http://localhost:3000/api/refresh
Content-Type: application/json

{
    "refresh":"a88d7720-fc03-4602-84f3-dcad913ed737"
}

###
POST http://localhost:3000/api/sessao/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NDYzMzFkLTNlMTMtNDNjNS04YjMzLTkwM2M3YWE4ODVhZCIsInJvbGUiOjAsIm5vbWUiOiJBbmEgU2lsdmEiLCJpYXQiOjE3ODczNDM2OTMsImV4cCI6MTc4NzM0NDE3M30.TKaMFod1ZwLgi399Cu3yKVoMS15_2iDOtGUJ5blAe5E
Content-Type: application/json

{
    "sessao_id":"00b7e430-8342-48ed-93f3-1814568f3d19",
    "quantia":"2000"
}