-- AlterTable
ALTER TABLE "agendas" ADD COLUMN     "disponibilidade" JSONB;

-- AlterTable
ALTER TABLE "sessoes" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "inicio" DROP NOT NULL,
ALTER COLUMN "inicio" DROP DEFAULT;
